---
- name: "List local rules directory"
  local_action: ansible.builtin.command ls {{ playbook_dir }}/{{ suricata_local_rules_dir }}
  register: dir_out
  when: suricata_local_rules_dir is defined and suricata_local_rules_dir != ""
  become: false

- name: "Upload custom rules"
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/{{ suricata_local_rules_dir }}/{{ item }}"
    dest: "{{ suricata_default_rule_path }}/"
    owner: "{{ suricata_user }}"
    group: "{{ suricata_group }}"
    mode: '0644'
  with_items: "{{ dir_out.stdout_lines }}"
  when: suricata_default_rule_path is defined and suricata_default_rule_path != "" and suricata_local_rules_dir is defined and suricata_local_rules_dir != ""

- name: "Register custom rules"
  set_fact:
    suricata_custom_rules: "{{ dir_out.stdout_lines }}"
  when: dir_out is defined

- name: "Find local rules paths"
  local_action: 
    module: ansible.builtin.find
    path: "{{ playbook_dir }}/{{ suricata_local_rules_dir }}/"
    file_type: file
    recurse: yes
  register: rules_list
  when: suricata_local_rules_dir is defined and suricata_local_rules_dir != ""
  become: false
  no_log: true

- name: "Set rules list if not defined"
  set_fact:
    suricata_rule_files: []
  when: suricata_rule_files is not defined

- name: "Append local rules list"
  set_fact:
    suricata_rule_files: "{{ suricata_rule_files + [ item.path|regex_replace(playbook_dir, '')|regex_replace(suricata_local_rules_dir, '')|regex_replace('^/+(.*)$', '\\1') ] }}"
  with_items: "{{ rules_list.files }}"
  no_log: true

- name: "Configure suricata"
  ansible.builtin.template:
    src: "etc/suricata/suricata.yaml.j2"
    dest: "{{ suricata_conf_file }}"
    owner: "{{ suricata_user }}"
    group: "{{ suricata_group }}"
    mode: 0640
