---
- name: Gather facts
  ansible.builtin.gather_facts:

- name: System specific suricata installation
  ansible.builtin.include_tasks:
    file: "{{ item }}"
    apply:
      tags:
        suricata_install
  with_first_found:
    - "install/{{ ansible_distribution | lower }}/{{ ansible_distribution_major_version | lower }}.yml"
    - "install/{{ ansible_distribution | lower }}/{{ ansible_distribution_version | lower }}.yml"
    - "install/{{ ansible_distribution | lower }}/{{ ansible_distribution_release | lower }}.yml"
    - "install/{{ ansible_distribution | lower }}/{{ ansible_distribution | lower }}.yml"
    - "install/{{ ansible_os_family | lower }}.yml"
  tags:
    suricata_install