---
dependency:
  name: galaxy
driver:
  name: docker
# lint: |
#   set -e
#   yamllint .
#   ansible-lint
platforms:
  - name: bind_fedora37
    image: geerlingguy/docker-fedora37-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
