---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: bind_fedora36
    image: geerlingguy/docker-fedora36-ansible:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
